Test fatima
techtory/webana-nextjs-project pull request #3
Opened 2021-04-02 13:45 UTC by fatimaaurangzeb0640

Portfolio and Case Study components are almost complete. Only the background image and css is left. I have started working on the Blog component now. I have tried to finish those parts first that I found similar in all the three mentioned components.

2021-04-04 22:22 UTC, Techtroy-Dev commented on pages/blogs.js
> +                <div css={css`
We are missing a key prop here this will give you Each child in an array should have a unique "key" prop error if you check in your console. Can we add a key here like this key={image.id}

2021-04-04 22:42 UTC, SamroonMichael requested changes
Added my review on the code please check them. Also, we are using floats in CSS it's okay but I would suggest replacing it with a position as floats were cause issues sometimes. Thanks

2021-04-04 22:42 UTC, SamroonMichael commented on pages/blogs.js
> +                <div css={css`
We are missing a key prop here this will give you Each child in an array should have a unique "key" prop error if you check in your console. Can we add a key here like this key={image.id}

2021-04-04 22:42 UTC, SamroonMichael commented on pages/caseStudy.js
> +                <div css={css`
Same here as well missing the key prop

2021-04-04 22:42 UTC, SamroonMichael commented on pages/portfolio.js
> +        return (<CardImage imageSrc={image.src} imageAlt={image.alt} type={"portfolio"} height={480} width={330}></CardImage>
Here as well missing the key prop. In fact, here we can just use an arrow function and remove the return statement like this: {images.map(() => <CradImage />)} keeping is simple and lean code.

2021-04-04 22:42 UTC, SamroonMichael commented on src/components/Main-Components/CardImage.js
> +				props.type==="portfolio"?
After we check the condition in ternary operators of the props.type and show the image if it's true. For the else statement rather than not showing anything and passing an empty tag can we have an image not found text or a broken image icon there? This is just for aesthetic and UI

2021-04-04 22:42 UTC, SamroonMichael commented on src/components/Sub-Components/CardText.js
> +			{ props.type === "caseStudy" ?
You can chain the ternary operators here like props.type === "caseStudy" **?** do something ... **:**  props.type === "blogs" **?** do something ... **:**

2021-04-06 21:26 UTC, SamroonMichael commented on src/components/Main-Components/CardImage.js
> +				src={props.imageSrc} alt={props.imageAlt} height={props.height} width={props.width} />:
In the eles block, you are not stating anything.

2021-04-06 21:26 UTC, SamroonMichael commented on src/components/Sub-Components/CardText.js
> +        </p>:
Did chained the ternary operators as I mentioned above

2021-04-08 10:34 UTC, fatimaaurangzeb0640 commented on src/components/Main-Components/CardImage.js
> +				src={props.imageSrc} alt={props.imageAlt} height={props.height} width={props.width} />:
In the else block I have put a <p> tag that says "Image not found".

2021-04-08 10:37 UTC, fatimaaurangzeb0640 commented on src/components/Sub-Components/CardText.js
> +        </p>:
I am sorry I didn't understand. Can you explain it to me again? Did I not chain it how you wanted me to?

2021-04-11 04:36 UTC, merged