Home + Fonts
techtory/webana-nextjs-project pull request #4
Opened 2021-04-05 07:27 UTC by ahmed1hsn

I've created home page and added fonts (Green Lantern and Raleway).

2021-04-05 12:35 UTC, SamroonMichael requested changes
Overall good work fix those few things are run them see how it works

2021-04-05 12:35 UTC, SamroonMichael commented on components/home/best-solution.js
> +const Post = () => (
All our home page components have the same name variable which is **Post** please change each of them according to that component name as this is the best practice and would not cause any confusion.

2021-04-05 12:35 UTC, SamroonMichael commented on components/home/best-solution.js
> +export { Post }
Can we use **export default** then the component name here

2021-04-05 12:35 UTC, SamroonMichael commented on components/home/best-solution.js
> +import { css, jsx } from "@emotion/react";
I would suggest to always keep the style import at last after import react, other components and libs

2021-04-05 12:35 UTC, SamroonMichael commented on components/home/best-solution.js
> +                src="/webana-assets/fantasized-ideas-turn-into-reality.png"
The assets shouldn't be coming from the public/images folder?

2021-04-05 12:35 UTC, SamroonMichael commented on components/home/home.js
> +/** @jsx jsx */
Same comments as above

2021-04-05 12:35 UTC, SamroonMichael commented on components/home/what-we-do.js
> +/** @jsx jsx */
Same comments as above

2021-04-05 12:35 UTC, SamroonMichael commented on components/home/why-we-stand-out.js
> +/** @jsx jsx */
Same comments as above. But we can break this one more component like a card component which takes in the icon, heading, and text props. You can use this a parent component and have card as a child component in it.

2021-04-05 12:35 UTC, SamroonMichael commented on components/layout.js
> +/** @jsx jsx */
There is already a layout component in the folder structure which is a wapper over all the pages. I don't think you pull the master branch before making changes. This layout component is for what purpose?

2021-04-05 12:35 UTC, SamroonMichael commented on pages/index.js
> +import * as wwso from "../components/home/why-we-stand-out"
This is okay but I would suggest using like this **import Home from '../components/home/home'** for all the import components. Of course the component names and path will be different I am just giving an example.

2021-04-05 12:35 UTC, SamroonMichael commented on shared/sidebar.js
> +const MyLink = props => (
Where are we getting these props from?

2021-04-05 13:07 UTC, ahmed1hsn commented on components/home/best-solution.js
> +                src="/webana-assets/fantasized-ideas-turn-into-reality.png"
You are right. it's public/webana-assets/.

2021-04-06 21:43 UTC, SamroonMichael reviewed
Overall looks good but there are 3 things I need a bit of fix:
1) /** @jsx jsx */ and import {css, jsx} from "@emotion/react" please push it down after the other imports. Style imports should be separated then others.
2) Please use the Layout component and Head component on all pages.
3) Our images are still coming from /webana-assets/ like I mention before it should be public/images

2021-04-07 05:22 UTC, ahmed1hsn commented
1. https://emotion.sh/docs/css-prop#jsx-pragma
2. Using them already.
3. public folder is default for assets, so /webana-assets/ is actually public/webana-assets/,  I changed the name /webana-assets/ to /images/ so new directory path is public/images/.

2021-04-11 04:30 UTC, merged